### ISSUE TITLE
Codecov defaults

### ISSUE THREAD

**Issue by dgasmith** [choderalab/cookiecutter-python-comp-chem#7]
I have found Codecov quite verbose and annoying without some modification. To automatically tone down the issues I usually setup a `.codecov.yml` with the following options:

```
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
```

Happy to discuss and/or modify them.
